language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - os

before_script: 

script:
    - qmake -project "CONFIG += qtestlib"
    - qmake Word-Flow/Word-Flow.pro
    - make
    - cd build
    - ctest —output-on-failure



